/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Page;

import Database.config;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.Button;
import Page.TambahSupplier;

/**
 *
 * @author ABDULLAH MUCHSIN
 */
public class HalamanSupplier extends javax.swing.JPanel {

    /**
     * Creates new form HalamanMenu
     */
    public HalamanSupplier() {
        initComponents();
        dataTable();
         // TODO add your handling code here:
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new rojeru_san.complementos.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        cr = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Halaman Suplier");

        tabel.setForeground(new java.awt.Color(255, 255, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Suplier", "Nama Suplier", "Alamat"
            }
        ));
        tabel.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tabel.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tabel.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tabel.setColorSelBackgound(new java.awt.Color(153, 139, 108));
        tabel.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tabel.setFuenteFilas(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        tabel.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tabel.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabel.setGrosorBordeFilas(0);
        tabel.setGrosorBordeHead(0);
        tabel.setRowHeight(40);
        jScrollPane1.setViewportView(tabel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cr.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        cr.setText("Cari Suplier");
        cr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crMouseClicked(evt);
            }
        });
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        cr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crKeyPressed(evt);
            }
        });

        cari.setBackground(new java.awt.Color(179, 162, 125));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carii.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari)
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setBackground(new java.awt.Color(153, 139, 108));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jButton1.setText("Tambah Suplier");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = (Statement) config.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * suplier where " 
                    + "kode_suplier ='" + cr.getText() + "';");
            DefaultTableModel tbl = new DefaultTableModel();
            cr.setText("");
            tbl.addColumn("Kode suplier");
            tbl.addColumn("Nama Suplier");
            tbl.addColumn("Alamat");
      
            
            
            tabel.setModel(tbl);       
            while (res.next()) {
                tbl.addRow(new Object[]{
                   res.getString("kode_Suplier"),
                   res.getString("nama_suplier"),
                   res.getString("alamat"),
                  
                });                
                tabel.setModel(tbl);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah");}
        
    }//GEN-LAST:event_cariActionPerformed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crActionPerformed

    private void crMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseClicked
        // TODO add your handling code here:
        cr.setText("");
    }//GEN-LAST:event_crMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void crKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            try {
          Statement statement = (Statement) config.getConnection().createStatement();
          ResultSet res = statement.executeQuery("select * suplier where " 
                    + "kode_suplier ='" + cr.getText() + "';");
            DefaultTableModel tbl = new DefaultTableModel();
            cr.setText("");
            tbl.addColumn("Kode suplier");
            tbl.addColumn("Nama Suplier");
            tbl.addColumn("Alamat");
            tbl.addColumn("Aksi");
      
            
            
            tabel.setModel(tbl);       
            while (res.next()) {
                tbl.addRow(new Object[]{
                   res.getString("kode_Suplier"),
                   res.getString("nama_suplier"),
                   res.getString("alamat"),
                 
                  
                });                            
                tabel.setModel(tbl);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah");}
        
        }
    }//GEN-LAST:event_crKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField cr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tabel;
    // End of variables declaration//GEN-END:variables
    
public void dataTable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Supplier");
        tbl.addColumn("Nama Supplier");
        tbl.addColumn("Alamat");
        tabel.setModel(tbl);  
        
        try{            
            Statement statement = (Statement) config.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from suplier");
            while (res.next()) {
                tbl.addRow(new Object[]{
                   res.getString("kode_suplier"),
                   res.getString("nama_suplier"),
                   res.getString("alamat_suplier"),
                });
                tabel.setModel(tbl);
            }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah");
        }
    }    

    private void showForm(TambahMenu tambahMenu) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
